### ISSUE TITLE
当增加多渠道配置的时候会报错

### ISSUE THREAD

**Issue by keternity** [ximsfei/Stark#6]
![image](https://user-images.githubusercontent.com/16664891/44083818-9f31cd0e-9fe7-11e8-8ea0-40c8840f379c.png)

当增加productFlavors后，编译gradle会报Cannot access first() element from an empty Iterable。

![image](https://user-images.githubusercontent.com/16664891/44083861-b7089282-9fe7-11e8-9b78-0efcd7954057.png)

去除了productFlavors后，就可以了。。。

**Comment by ximsfei** [comment]
已修复

**Comment by keternity** [comment]
ok
